---
- name: Extract and prepare login data for Grafana
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure log directory exists on control node
      delegate_to: localhost
      ansible.builtin.file:
        path: "./grafana_logs"
        state: directory
        mode: '0755'
      run_once: true

    - name: Fetch and filter journal data
      ansible.builtin.shell:
        cmd: |
          journalctl -o json --output-fields=MESSAGE,TLOG_REC -S "today" _COMM=tlog-rec-session
      register: tlog_entries

    - name: Gather start time
      ansible.builtin.set_fact:
        tlog_start_time: "{{ tlog_result.stdout | from_json.tlog_entries.start }}"

    - name: Use the 'start' variable in a debug message
      ansible.builtin.debug:
        msg: "The tlog recording started at: {{ tlog_start_time }}"
        
#    - name: Debugging a variable
#      debug:
#       var: tlog_entries

 #   - name: set var
 #     set_fact:
 #       date_var: "{{ tlog_entries[start] | strftime('%Y-%m-%dT%H:%M:%SZ') }}"

 #   - name: Debugging a date_var
 #     debug:
 #      var: date_var

    - name: Process and format log data
      ansible.builtin.template:
        src: template_logins.j2
        dest: "./grafana_logs/{{ inventory_hostname }}-logins.json"
      vars:
        log_entries: "{{ tlog_entries.stdout | from_json_list | default([]) }}"
      delegate_to: localhost
