---
- name: Pull login information from tlog session recordings
  hosts: all
  become: yes
  tasks:
    - name: Query journal for tlog login events
      ansible.builtin.command:
        cmd: journalctl -o json_pretty _COMM=tlog-rec-session
      register: tlog_entries
      failed_when: tlog_entries.rc != 0 and tlog_entries.rc != 1

    - name: Display login information
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ tlog_entries.stdout_lines }}"
      loop_control:
        label: "{{ item | from_json | json_query('user') }}"
      when: tlog_entries.stdout_lines is defined and item | from_json | json_query('user') is defined
