---
- name: Extract and prepare login data for Grafana
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure log directory exists on control node
      delegate_to: localhost
      ansible.builtin.file:
        path: "./grafana_logs"
        state: directory
        mode: '0755'
      run_once: true

    - name: Fetch and filter journal data
      ansible.builtin.shell:
        cmd: |
          journalctl -o json --output-fields=MESSAGE,TLOG_REC -S "today" _COMM=tlog-rec-session
      register: tlog_entries

    - name: Process and format log data
      ansible.builtin.template:
        src: template_logins.j2
        dest: "./grafana_logs/{{ inventory_hostname }}-logins.json"
      vars:
        log_entries: "{{ tlog_entries.stdout | from_json_list | default([]) }}"
      delegate_to: localhost
