---
- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Register as user with password and auto-subscribe to available content
  community.general.redhat_subscription:
    state: present
    username: "{{ rh_username }}"
    password: "{{ rh_password }}"
