---
- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Register as user with password and auto-subscribe to available content
  redhat_subscription:
    state: present
    username: "{{ rh_username }}"
    password: "{{ rh_password }}"

- name: restart machine
  ansible.builtin.command: shutdown -r now "Ansible updates triggered"
    async: 0
    poll: 0
    ignore_errors: True
    when:
      reboot is defined

- name: Waiting for server to come back up
  local_action: wait_for host= "{{ inventory_hostname }}" port=22 state=started

- name: Fix /etc/hosts removing the old hostname
  tags:
    - hosts
  lineinfile:
    state=present
    dest=/etc/hosts
    line= "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"
    regexp= "{{ ansible_default_ipv4.address }}"
  when:
    ansible_fqdn != inventory_hostname

- name: Validate ansible_fqdn == inventory_hostname
  tags:
    - validate
  assert:
    that:
      ansible_fqdn == inventory_hostname
